### ISSUE TITLE
Enable jslint in html file

### ISSUE THREAD

**Issue by xiaohan2012** [hallettj/jslint.vim#43]
How to enable jslint when editing html file?

**Comment by hallettj** [comment]
Jslint.vim is only active when Vim's filetype is set to "javascript".  You
can turn on more than one filetype at a time by separating types with dots,
like this:

```
:setfiletype html.javascript
```

However, you might find the result difficult to work with, since jslint
will highlight the HTML portions of your file as errors.

You might have an easier time if you combine jslint.vim with another plugin
called [NrrwRgn](https://github.com/chrisbra/NrrwRgn).  That plugin lets you edit a selected portion of a file
in another buffer, where you can set the filetype independently.

On May 5, 2012 1:03 AM, "xiaohan2012" <
reply@reply.github.com>
wrote:

**Comment by xiaohan2012** [comment]
thanks!
